### ISSUE TITLE
CFBundleIdentifier Does Not Exist

### ISSUE THREAD

**Issue by GioValentin** [opentok/opentok-react-native-samples#10]
"Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/BasicVideoChat.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist" 

I am getting this issue at  "npm run ios" 

I haven't tried Andriod but I have not been able to get this to work once.

**Comment by jraleman** [comment]
Try running the following command, but make sure to repalce `${ ProjectName }`with either `Signaling` or `BasicVideoChat`

```
node node_modules/react-native/local-cli/cli.js \
bundle --entry-file='index.ios.js' \
       --bundle-output='./ios/${ ProjectName }/main.jsbundle' \
       --platform='ios' \
       --assets-dest='./ios' \
       --dev=false
```

Hope this helps you out!

**Comment by msach22** [comment]
@GioValentin were you able to get it going?

@jraleman Hmm, isn't that for bundling the js into the `main.jsbundle` file and having the js load from it rather than the local node server?

**Comment by msach22** [comment]
@GioValentin I'm going to go ahead and close this issue, but please feel free to re-open if the issue still persists!

**Comment by CyrusZei** [comment]
if you check the logs you will see that it is missing something

`OpenTok/OpenTok.h' file not found`

If it does not support react-native please write it on the README.MD file

**Comment by msach22** [comment]
@CyrusZei We have an open bug: https://github.com/opentok/opentok-react-native/issues/235 where we're seeing an issue with Cocoapods 1.6.0. Are you seeing the same thing?

**Comment by CyrusZei** [comment]
yup, had been struggling with it all day and now this is my last resort

**Comment by CyrusZei** [comment]
I am trying to avoid pod installation and rather do it manually, but it is somewhat hard to do all the steps since not all the steps are in the README file.

**Comment by msach22** [comment]
@CyrusZei Sorry to hear that it's not working - we only support the iOS installation for OpenTok React Native via Cocoapods at this time, but I'll explore a solution without Cocoapods. I've filed an issue on the library repo to find an alternative. https://github.com/opentok/opentok-react-native/issues/246

For reference, you can download the iOS SDK here: https://tokbox.com/developer/sdks/ios/

**Comment by CyrusZei** [comment]
Okej, let me try the pod and see if I can get it working and I will write down all the steps that I am doing

**Comment by CyrusZei** [comment]
1.`yarn add opentok-react-native`
2.open Podfile and add `pod 'OpenTok', '2.15.3'`
3.`pod install`
4.`react-native link opentok-react-native`
