### ISSUE TITLE
OTSessionErrorDomain error 1010 

### ISSUE THREAD

**Issue by adamchenwei** [opentok/opentok-react-native-samples#115]
I followed the steps in the README.md, I was able to get the app started, filled in the api key, token, session id that is already functional in our account for vonage opentok. But I got blank screen on emulator and errors like following when started the app in ios emulator in macbook pro (intel processor):

```
 LOG  Running "BasicVideoChat" with {"rootTag":11,"initialProps":{}}
 LOG  OTRN JS: There was an error:  logging
 LOG  OTRN JS: There was an error:  {"code": 1010, "message": "The operation couldn’t be completed. (OTSessionErrorDomain error 1010.)"}
 LOG  OTRN JS: There was an error:  logging
 LOG  OTRN JS: There was an error:  {"code": 1010, "message": "The operation couldn’t be completed. (OTSessionErrorDomain error 1010.)"}
 LOG  OTRN JS: There was an error:  logging
```

![Screen Shot 2022-09-13 at 3 34 49 PM](https://user-images.githubusercontent.com/4201698/189993323-fd443dbc-04d6-4350-8afa-3b816cdc4bb0.png)

I was eventually able to get the android and ios demo running, ONLY if I ran them directly viao Android Studio or XCode. 
For android: I am not able to start the app when do `yarn android` 
For ios: I am able to start the app, but the actual video section never appear.
For both, when a change is done in react native app source, the video section will disappear again, without any error

**Comment by abdulajet** [comment]
Please reopen if the issue persists. Thank you
