### ISSUE TITLE
OpenTok/OpenTok.h' file not found

### ISSUE THREAD

**Issue by bizzychamps** [opentok/opentok-react-native-samples#12]
I've cleared node modules, cache, reinstalled etc., but experiencing the error message `OpenTok/OpenTok.h' file not found`. I'm using the version  0.8.2

React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.5
      CPU: x64 Intel(R) Core(TM) i5-2435M CPU @ 2.40GHz
      Memory: 25.43 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.4.0 - ~/.nvm/versions/node/v8.4.0/bin/node
      npm: 6.1.0 - ~/.nvm/versions/node/v8.4.0/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
    IDEs:
      Android Studio: 3.1 AI-173.4819257
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.4.1 => 16.4.1 
      react-native: ^0.56.0 => 0.56.0 
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7

**Comment by smakosh** [comment]
Same issue

**Comment by CyrusZei** [comment]
yeah, so how is this happening ? 

Is this even alive ?

**Comment by smakosh** [comment]
check inside the `Headers` folder located here `/ios/Pods/Headers` and see if there is a folder for openTok

**Comment by CyrusZei** [comment]
no, no nothing.

**Comment by CyrusZei** [comment]
they really should update the README file with steps that works instead of just some part of it

**Comment by smakosh** [comment]
you will have to downgrade cocapods and run `pod deintegrate` and `pod install` again and check if the pre-compiled headers are generated, otherwise you will have to get it somewhere to put it there...

**Comment by CyrusZei** [comment]
yeah, don't feel like working anymore with OpenTok. I will look for another service. Anything you can recommend that works with react-native ? live stream broadcasting?

**Comment by smakosh** [comment]
nope sorry, I personally drag & drop the openTok pre-compiled headers each time I run `pod install`

**Comment by CyrusZei** [comment]
I am doing 
1.yarn install opentok-react-native
2.react-native link opentok-react-native
3I get the opentok xcode project and drag it into the libraries inside of my xcode project

**Comment by smakosh** [comment]
`yarn add` not `yarn install`

**Comment by smakosh** [comment]
And that's different than what's mentioned on the docs, don't forget the pods steps

**Comment by CyrusZei** [comment]
yes I just typed wrong here, but I am using yarn add for this, but still no luck

**Comment by CyrusZei** [comment]
there should be a manual linking stuffs on ios instead. Pod install fuckes react native up

**Comment by mgiorgi-github** [comment]
Hi, I’ve the same problem, what is the right cocoapods version? I’have the last and the headers folder is empty, can you share the folder content? Thanks

**Comment by smakosh** [comment]
https://drive.google.com/open?id=1WoPWubE8L6jKy49JDvTCJTZrJWF2aYYO

**Comment by mgiorgi-github** [comment]
Thanks for share ... after some attempts i've created OpenTok folder inside Pods folder but when i run
"react-native link opentok-react-native" the build fails with the same message: 'OpenTok / OpenTok.h' file not found.
This is my Pods folder:
![Schermata 2019-04-19 alle 15 08 32](https://user-images.githubusercontent.com/24822858/56425538-0d1b3400-62b5-11e9-9933-a41aef25dd44.png)

**Comment by smakosh** [comment]
Put the folder I linked within `/Pods/Headers/private` & `/Pods/Headers/public`

**Comment by mgiorgi-github** [comment]
Yes... now it compile!
Thanks

**Comment by joelgetaction** [comment]
Hey @msach22 I am unable to compile - getting `OpenTok/OpenTok.h file not found`.  Any idea how to fix this?  I really want to consider OpenTok for my video startup but if I can't get your samples to compile I can't use your SDK ... :-(

Hey @smakosh and @mgiorgi-github - how did you make your fix?  I don't understand what I'm supposed to do to fix things to work like you did ... Any help appreciated!  Thanks.

**Comment by joelgetaction** [comment]
> Put the folder I linked within `/Pods/Headers/private` & `/Pods/Headers/public`

What do you mean by this @smakosh ?  Which folder do I put and where and which setting do I need to change?

**Comment by joelgetaction** [comment]
OK, here's what worked for me (after `pod install`):
```
pushd opentok-react-native-samples/BasicVideoChat/ios/Pods/Headers
mkdir public
cp ../../OpenTok/OpenTok.framework/Headers/*.h public
```
Then it compiled.

@msach22 - it seems there's either an error in your project somewhere or the README needs to be updated with these steps.  Can we do that?  Otherwise this is a frustrating first experience when the samples don't work ... :-). Thanks!

**Comment by msach22** [comment]
@joelgetaction Thanks for adding this info - are you using Cocoapods 1.6.0?

**Comment by joelgetaction** [comment]
@msach22 you're welcome!  I'm using Cocoapods 1.6.1.

**Comment by msach22** [comment]
Hi Folks, we have a fix for this coming up - you can use it with Cocoapods 1.6.x. 

I'll patch the library this week :)

**Comment by msach22** [comment]
Thanks for the feedback - the fix has been deployed with `opentok-react-native v0.10.2`
