### ISSUE TITLE
Error - Native module can't be null

### ISSUE THREAD

**Issue by ricardolousada** [opentok/opentok-react-native-samples#16]
I have tried the supplied code and I got:

1: the following warning in Visual Studio Code - Could not find a declaration file for module 'opentok-react-native'. '/Users/rlousada/Documents/Developer/TokBox/tokboxclient/node_modules/opentok-react-native/src/index.js' implicitly has an 'any' type.
  Try `npm install @types/opentok-react-native` if it exists or add a new declaration (.d.ts) file containing `declare module 'opentok-react-native';`ts(7016)  

2- When running I got an error (please check) attached image.

Can someone please help?

Thank you.

![tokbox_error](https://user-images.githubusercontent.com/4757712/54835339-d05e1c00-4cb9-11e9-91fa-f2950887c021.png)

**Comment by msach22** [comment]
@ricardolousada Apologies for the delay in getting back to you on this one. I've updated the samples and this issue has been fixed. Please use the latest code in the repo.
