### ISSUE TITLE
Archiving video chat

### ISSUE THREAD

**Issue by QuevedoIB** [opentok/opentok-react-native-samples#19]
Is there any explanation on how to implement archiving to the video chat sample? I'm trying to find a way to implement something similar to skype that can be recorded I've been reading the tokbox documentation and looks that it can be achieved but it's quite confusing how to, at least for a beginner like me. Any help would be really appreciated! Thanks in advance

**Comment by vinoth12594** [comment]
You got any solution for this

**Comment by msach22** [comment]
Take a look at this archiving guide that will walk you through all the steps: https://tokbox.com/developer/guides/archiving/

Note that archiving is a server side API call.

**Comment by vinoth12594** [comment]
Thanks for quick replay. I have another doubt how I disconnect call manually.
