### ISSUE TITLE
“Native module cannot be null” while using openTok reactnative

### ISSUE THREAD

**Issue by Prachithra** [opentok/opentok-react-native-samples#35]
i am just trying to implement Video implementation in my react native app. For that i am using "opentok-react-native". But Import the library using the code below gives an error:

     import { OTSession, OTPublisher, OTSubscriber } from 'opentok-react-native';

Error:
      
        "Native module cannot be null"

**Comment by 3mpe** [comment]
In version 0.59.9 I solved it as follows;
I added ": modular_headers => true" to the PodFile file. i saw it work.

`
 pod 'React', :path => '../node_modules/react-native', :subspecs => [
      'Core',
      'CxxBridge',
      'RCTAnimation',
      'RCTBlob',
      'RCTText',
      'RCTNetwork',
      'RCTWebSocket',
      'RCTImage',
      'RCTLinkingIOS',
      'DevSupport',
    ], :modular_headers => true

    pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
    pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
    pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
    pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

    pod 'opentok-react-native', :path => '../node_modules/opentok-react-native'
`

**Comment by romreed** [comment]
@3mpe Why sample not working then i try upgrade to "react-native": "0.61.5"?

**Comment by 3mpe** [comment]
I use 59.9 in all of my projects and I had no chance to upgrade any of them. I will look again when I have a chance to try 0.61.5, but it doesn't seem to be resolved without podfile as it expects you to use modular_headers => true.

**Comment by romreed** [comment]
@3mpe I can't install at the clear project and try upgrade to 0.61.5 without success.

**Comment by 3mpe** [comment]
It works in 0.59.9 version, what is your react-native version?

**Comment by romreed** [comment]
@3mpe  0.61.5

**Comment by velykovits** [comment]
Yes, because they downgraded RN version to 0.59 on purpose to avoid AndroidX migration:
https://github.com/opentok/opentok-react-native-samples/commit/56dc44df47ddc4e158ab392836c1915691db3781
