### ISSUE TITLE
Annotation over Video Stream

### ISSUE THREAD

**Issue by JamieCorkhill** [opentok/opentok-react-native-samples#42]
Hello.

My project includes two users communicating with one another within a "room", sharing audio and video between one another. Platform wise, this could be Desktop/Web JavaScript to Mobile React Native, or Mobile React Native to Mobile React Native.

I'd like, when using Mobile, to be able to have both users annotate their video stream.

Is that possible to do via Signaling with the OpenTok React Native library?

Thank you,
Jamie

**Comment by mzruiz** [comment]
A bit late but hope this helps someone.

We've been able to achieve this by placing a component adjacent to the <OTSession> component.

i.e.,
```
<SafeAreaView style={styles.container}>
  <OTSession apiKey={vonageAPIKey} sessionId={sessionId} token={token}>
    <OTPublisher style={{width: DEVICE_WIDTH, height: DEVICE_HEIGHT}} />
  </OTSession>
  <Button />
</SafeAreaView>

...

const styles = StyleSheet.create({
  container: {
    height: <Device Height>,
    flexDirection: 'row', // The button will now show without this
  }
});
```

This then allows us to place components 'on top' of the video stream.

Hope this helps.
