### ISSUE TITLE
Error when starting the project - Unable to resolve module `warnOnce`

### ISSUE THREAD

**Issue by SheereenHamza** [opentok/opentok-react-native-samples#52]
{"originModulePath":"node_modules\\react-native\\Libraries\\react-native\\react-native-implementation.js","targetModuleName":"warnOnce","message":"Unable to resolve module `warnOnce` from `node_modules\\react-native\\Libraries\\react-native\\react-native-implementation.js`: warnOnce could not be found within the project.\n\nIf you are sure the module exists, try these steps:\n 1. Clear watchman watches: watchman watch-del-all\n 2. Delete node_modules: rm -rf node_modules and run yarn install\n 3. Reset Metro's cache: yarn start --reset-cache\n 4. Remove the cache: rm -rf /tmp/metro-*","errors":[{"description":"Unable to resolve module `warnOnce` from `node_modules\\react-native\\Libraries\\react-native\\react-native-implementation.js`: warnOnce could not be found within the project.\n\nIf you are sure the module exists, try these steps:\n 1. Clear watchman watches: watchman watch-del-all\n 2. Delete node_modules: rm -rf node_modules and run yarn install\n 3. Reset Metro's cache: yarn start --reset-cache\n 4. Remove the cache: rm -rf /tmp/metro-*"}],"name":"Error","stack":"Error: Unable to resolve module `warnOnce` from `node_modules\\react-native\\Libraries\\react-native\\react-native-implementation.js`: warnOnce could not be found within the project.\n\nIf you are sure the module exists, try these steps:\n 1. Clear watchman watches: watchman watch-del-all\n 2. Delete node_modules: rm -rf node_modules and run yarn install\n 3. Reset Metro's cache: yarn start --reset-cache\n 4. Remove the cache: rm -rf /tmp/metro-*\n    at ModuleResolver.resolveDependency (C:\\Users\\Sheereen\\AppData\\Roaming\\npm\\node_modules\\@react-native-community\\cli\\node_modules\\metro\\src\\node-haste\\DependencyGraph\\ModuleResolution.js:186:15)\n    at ResolutionRequest.resolveDependency (C:\\Users\\Sheereen\\AppData\\Roaming\\npm\\node_modules\\@react-native-community\\cli\\node_modules\\metro\\src\\node-haste\\DependencyGraph\\ResolutionRequest.js:52:18)\n    at DependencyGraph.resolveDependency (C:\\Users\\Sheereen\\AppData\\Roaming\\npm\\node_modules\\@react-native-community\\cli\\node_modules\\metro\\src\\node-haste\\DependencyGraph.js:287:16)\n    at Object.resolve (C:\\Users\\Sheereen\\AppData\\Roaming\\npm\\node_modules\\@react-native-community\\cli\\node_modules\\metro\\src\\lib\\transformHelpers.js:267:42)\n    at C:\\Users\\Sheereen\\AppData\\Roaming\\npm\\node_modules\\@react-native-community\\cli\\node_modules\\metro\\src\\DeltaBundler\\traverseDependencies.js:434:31\n    at Array.map (<anonymous>)\n    at resolveDependencies (C:\\Users\\Sheereen\\AppData\\Roaming\\npm\\node_modules\\@react-native-community\\cli\\node_modules\\metro\\src\\DeltaBundler\\traverseDependencies.js:431:18)\n    at C:\\Users\\Sheereen\\AppData\\Roaming\\npm\\node_modules\\@react-native-community\\cli\\node_modules\\metro\\src\\DeltaBundler\\traverseDependencies.js:275:33\n    at Generator.next (<anonymous>)\n    at asyncGeneratorStep (C:\\Users\\Sheereen\\AppData\\Roaming\\npm\\node_modules\\@react-native-community\\cli\\node_modules\\metro\\src\\DeltaBundler\\traverseDependencies.js:87:24)"}

**Comment by abdulajet** [comment]
Please check the lastest version of the projects if you are still having this issue
