### ISSUE TITLE
Whiteboard and screen sharing support?

### ISSUE THREAD

**Issue by mthirukavi** [opentok/opentok-react-native-samples#54]
Is it possible to have white board and screen sharing on using this library?

**Comment by mzruiz** [comment]
Hola,

A bit late but hope this helps someone.

I posted a solution to the whiteboard question over on #42. We've used [react-native-svg](https://github.com/react-native-community/react-native-svg) to place a layer on top of the screen to handle annotations.

**Comment by abdulajet** [comment]
Thanks!
