### ISSUE TITLE
 screen sharing not working outside application

### ISSUE THREAD

**Issue by 10xamohan** [opentok/opentok-react-native-samples#60]
I am using opentok-react-native: "0.14.0" library for my react native projects. Somehow I managed to enable screen share functionality by adding one more publisher with screen share properties.

It works and I am able to view the screen at the other end. But now I am stuck with issues:

Sharing is not working outside the application.
Also within the application when I navigate to other routes my component unmounts which is obvious and screen share disconnects.
So I got stuck with the sharing screen of one component only.

Any Suggestion. Help

Thanks

**Comment by abdulajet** [comment]
Please open an issue on the `opentok-react-native` repo
