### ISSUE TITLE
Publisher not able to see subscriber video 

### ISSUE THREAD

**Issue by pankajdreamsoft** [opentok/opentok-react-native-samples#77]
My configurations are below

    "opentok-react-native": "^0.15.0",
    "react": "16.13.1",
    "react-native": "^0.63.4",

Current Behavior : Publisher can see own video not subscriber video stream but subscriber able to see both own and publisher video stream.

Expected Behavior : Publisher should able to see the video of subscriber video stream.

Please help me how can i solve this issue?

**Comment by abdulajet** [comment]
Please retry with the latest versions of the sample projects
