### ISSUE TITLE
Native Module OTSessionManager tried to Overrid OTSessionManager

### ISSUE THREAD

**Issue by jraleman** [opentok/opentok-react-native-samples#8]
I get this error after:
- `git clone https://github.com/opentok/opentok-react-native-samples`
- `cd opentok-react-native-samples`
- `npm i`
- `react-native link`

I experience this while running the Android version with a simulator. I still haven't test it with iOS.

**Comment by jraleman** [comment]
Got it to work under Android. 
Made a PR: https://github.com/opentok/opentok-react-native-samples/pull/9

Still need to test this under iOS, should be able to in a couple of hours.

**Comment by msach22** [comment]
Thanks for fixing this! Closing this issue!
