### ISSUE TITLE
Unable to run sample code on iOS

### ISSUE THREAD

**Issue by RashmiPatiliLink** [opentok/opentok-react-native-samples#80]
**Please try again later.**
invalid symlink at /Users/macmini/Library/Developer/CoreSimulator/Devices/1FCF8B6D-08B1-40E1-B2F5-61CA5DE3D1BD/data/Library/Caches/com.apple.mobile.installd.staging/temp.FfjwvA/extracted/tokreact.app/node_modules/.bin/uuid
Always getting this error

**Comment by abdulajet** [comment]
Please try the latest versions of the project
